CREATE DATABASE TBD;
GO

USE TBD;

CREATE TABLE users(
    id INT NOT NULL PRIMARY KEY IDENTITY,
	email NVARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(64) NOT NULL, -- SHA-256 hash
	full_name NVARCHAR(255) NOT NULL,
);